### ISSUE TITLE
Tabs shouldn't go to the left of pinned tabs

### ISSUE THREAD

**Issue by huyz** [valsorym/vscode-smart-tabs#1]
This extension doesn't seem to recognized pinned tabs. Tabs with modified content shouldn't be placed to the left of pinned tabs for two reasons:
1. Pinned tabs have already been manually designated to be placed to the left by the user
2. Right now, this extension incorrectly results in the modified tabs being pinned automatically

**Comment by valsorym** [comment]
@huyz Hello. Sorry for not replying for a long time. War and all of those things, you know what I mean...

Fixed these bugs and optimized the code. It looks like a working version. I hope it is still relevant and will bring you pleasure!
