### ISSUE TITLE
Move tab as soon as it is focused on?

### ISSUE THREAD

**Issue by jerpint** [valsorym/vscode-smart-tabs#2]
Is it possible to move a tab as soon as it is focused on, and not only when an edit gets made?

**Comment by valsorym** [comment]
> Is it possible to move a tab as soon as it is focused on, and not only when an edit gets made?

Hello!

I don't think it's a good idea!

But it wasn't a very difficult task either. So, I updated the extension to version `1.3.1` where there is an option `smart-tabs.reactionEvent`.

It defines the event in which the tab is moved: `onedit` - (default) when the tab content is edited; `onsave` - when the tab content is saved; `onfocus` - when the tab is focused; `onopen` - when the tab is opened; `none` - disable extension.

So, add something like this to your configuration:

```json
...
    "smart-tabs.activeFirst": true,
    "smart-tabs.fixedTabs": 3,
    "smart-tabs.debounceDelay": 300,
    "smart-tabs.reactionEvent": "onfocus", // <--- this way
...
```

I hope this helps you! Enjoy!
